name: run ktlint

on:
  push:
    branches: [master] 
  pull_request:
    branches: [master]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
          
      - uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('gradle-checksums.txt') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ hashFiles('gradle-checksums.txt') }}-
      
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: ktlint
        run: ./gradlew ktlintCheck

      - uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: ./**/build/reports/ktlint/